### ISSUE TITLE
Incorrect real Cartesian spherical harmonics formula

### ISSUE THREAD

**Issue by curtischong** [google-research/e3x#22]
On this webpage (https://e3x.readthedocs.io/stable/_autosummary/e3x.so3.irreps.spherical_harmonics.html), the definition of pi has a $r^{2k - l}$ term. However, in the code (https://github.com/google-research/e3x/blob/main/e3x/so3/_symbolic.py#L65), we are only multiplying by $r^{2k}$ we are not subtracting by l.

**Comment by OUnke** [comment]
Thank you for pointing out this typo in the documentation (the code is correct)! This will be fixed in the next version.
